/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MigrationsContract } from "./Migrations";
import { TodoListContract } from "./TodoList";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): MigrationsContract;
      require(name: "TodoList"): TodoListContract;
    }
  }
}

export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { TodoListContract, TodoListInstance } from "./TodoList";
